SELECT * FROM "EventsSpyUI.DbViews::AT_ENTIRE_USER_DATA" AS "USER_DATA" WHERE "USER_DATA"."USERNAME"='Paul' AND "USER_DATA"."PASSWORD"='Jason'

SELECT * FROM "EventsSpyUI.DbViews::AT_MY_CREATED_EVENTS" AS "EVENTS_USER" WHERE "EVENTS_USER"."USER_ID" = 1

SELECT * FROM "ACME"."LOB_INFO" AS "LOB_INFO"
