CREATE COLUMN TABLE "ACME"."EVENTS_USER"(
	"USER_ID" INTEGER NOT NULL PRIMARY KEY,
	"USERNAME" VARCHAR(20),
	"PASSWORD" VARCHAR(20) 	
);

INSERT INTO "ACME"."EVENTS_USER" VALUES(1,'Paul','Jason');
INSERT INTO "ACME"."EVENTS_USER" VALUES(2,'Prabakar','Reddy');
INSERT INTO "ACME"."EVENTS_USER" VALUES(3,'Persisa','Reddy');

CREATE COLUMN TABLE "ACME"."LOB_INFO"(
	"LOB_ID" INTEGER PRIMARY KEY,
	"LOB" VARCHAR(30)
);

INSERT INTO "ACME"."LOB_INFO" VALUES(1,'BI Analytics');
INSERT INTO "ACME"."LOB_INFO" VALUES(2,'Travel & Expense Management');

CREATE COLUMN TABLE "ACME"."USER_LOB"(
	"USER_ID" INTEGER,
	"LOB_ID" INTEGER,
	CONSTRAINT PK_USER_TEAM PRIMARY KEY("USER_ID","LOB_ID"),
	FOREIGN KEY ("USER_ID") REFERENCES "ACME"."EVENTS_USER"("USER_ID"),
	FOREIGN KEY ("LOB_ID") REFERENCES "ACME"."LOB_INFO"("LOB_ID")
);

INSERT INTO "ACME"."USER_LOB" VALUES(1,1);
INSERT INTO "ACME"."USER_LOB" VALUES(2,2);


CREATE COLUMN TABLE "ACME"."CREATED_EVENTS"(
	"EVENT_ID" INTEGER,
	"TITLE" VARCHAR(15),
	"DESCRIPTION" VARCHAR(200),
	"FOR_LOB_ID" INTEGER,
	"FOR_LOB" VARCHAR(30),
	"DATE_TIME" VARCHAR(30),
	"CAPACITY" INTEGER,
	"CURRENT_WAITLIST" INTEGER DEFAULT 0,
	"REGISTERED_NUMBER" INTEGER DEFAULT 0,
	CONSTRAINT PK_CREATED_EVENTS PRIMARY KEY("EVENT_ID")
)

INSERT INTO "ACME"."CREATED_EVENTS" VALUES
(1,'SAP TECHED','TECHED is back here you go!!!!',1,'BI Analytics','2017-08-26 09:00:00',500,0,0);
INSERT INTO "ACME"."CREATED_EVENTS" VALUES
(2,'SAP HACKATHON','Worlds biggest hackathon is here, let the innovation begin!!!!',2,'Travel & Expense Management','2017-08-31 09:00:00',90,0,0);


CREATE COLUMN TABLE "ACME"."USER_CREATED_EVENTS"(
    "USER_ID" INTEGER,
	"EVENT_ID" INTEGER,
	CONSTRAINT PK_USER_CREATED_EVENTS PRIMARY KEY("USER_ID","EVENT_ID"),
	FOREIGN KEY ("USER_ID") REFERENCES "ACME"."EVENTS_USER"("USER_ID"),
	FOREIGN KEY ("EVENT_ID") REFERENCES "ACME"."CREATED_EVENTS"("EVENT_ID")
);

INSERT INTO "ACME"."USER_CREATED_EVENTS" VALUES(1,2);
INSERT INTO "ACME"."USER_CREATED_EVENTS" VALUES(2,1);

CREATE COLUMN TABLE "ACME"."USER_REGISTERED_EVENTS_WITH_STATUS"(
	"USER_ID" INTEGER,
	"EVENT_ID" INTEGER,
	"STATUS" VARCHAR(20),
	CONSTRAINT PK_USER_REGISTERED_EVENTS PRIMARY KEY("USER_ID","EVENT_ID"),
	FOREIGN KEY ("USER_ID") REFERENCES "ACME"."EVENTS_USER"("USER_ID"),
	FOREIGN KEY ("EVENT_ID") REFERENCES "ACME"."CREATED_EVENTS"("EVENT_ID")
);

INSERT INTO "ACME"."USER_REGISTERED_EVENTS" VALUES(3,1);


Queries:

SELECT * FROM "ACME"."CREATED_EVENTS" AS "CREATED_EVENTS" WHERE "CREATED_EVENTS"."FOR_LOB"='BI Analytics' AND "CREATED_EVENTS"."INVITED"=0

UPDATE "ACME"."CREATED_EVENTS" AS "CREATED_EVENTS" SET "CREATED_EVENTS"."INVITED"=0 WHERE "CREATED_EVENTS"."FOR_LOB"='BI Analytics';

SELECT * FROM "ACME::AT_EVENTS_LOB_ID" AS "CREATED_EVENTS" WHERE "CREATED_EVENTS"."TEAM_ID"=1 AND "CREATED_EVENTS"."INVITED"=0;